votca/votca

- .travis.yml
- docker/set_env.sh
This will allow us to modify the environment in votca/votca without having to copy the `.travis.yml` file over to all the repos. (Except if we need more environments, 18 currently.)
Plus we could trigger builds more fine-grained, e.g. only build different gromacs versions for csg.
> Move travis environment into a script 

- .travis.yml
It seems TRAVIS_BUILD_STAGE_NAME doesn't get capitalized anymore,
even though the documentation says so.
Also reported here: https://github.com/mlflow/mlflow/issues/2631
> fix docker deploy

- CMakeModules/FindCLANG_FORMAT.cmake
- share/format/CMakeLists.txt
This reverts commit a10f9cae7941d90caa76b6c08e997b9a32edad22, partly reversing
changes made to 447b535fb0aee85d5a424281c12bb90e27982a84.
This too broken on Ubuntu triggering a fatal error (see https://groups.google.com/d/msg/votca/a2D4zoxhx6o/hGMhW9J5AwAJ), so reverting to the old scheme.
> Revert "Merge pull request #274 from votca/cmake_rm_find_clang_format"

- share/doc/conf.py.in
Used the [Python nbsphinx extension](https://nbsphinx.readthedocs.io/en/0.7.0/) to directly convert the Jupyter notebooks into Sphinx documentation.
> used nbsphinx to generate documentation

- share/doc/conf.py.in
In some linux distribution there is not available a suitable [nbsphinx converter](https://nbsphinx.readthedocs.io/en/0.7.1/) causing an error when generating the documentation.
*nbsphinx* error can be ignored with the `nbsphinx_allow_errors` flag
> allow errors in  nbsphinx

- .github/workflows/stable_cron.yml
To workaround the issue in https://github.community/t/scheduled-builds-of-non-default-branch/16306 that prevents scheduled action to run for non-default branches.
> CI: add crons for stable branch

- CMakeModules/FindCLANG_FORMAT.cmake
- share/format/CMakeLists.txt
Updated the findClangFormat so it finds the newest version first.
Also require version 10 exactly now.
> updated clang-format and require exact version

- .github/workflows/continuous-integration-workflow.yml
Gentoo buildenv builds are taking too long.
> GHA: drop gentoo

- share/doc/extract_xml_metadata.py
For the **XTP** calculators sometimes there are no arguments required and the `XML` files don't contain any useful information.
For those cases it is better to skip the table construction and just create an `rst` file with the help information.
> don't print table if no elements in rst

- share/doc/extract_xml_metadata.py
- Extract correctly the CSG properties' description
Previous I was extracting the description as:
```py
elem.get("text", "")
```
But the correct way is:
```py
elem.text
```
The problem is that the `get` method is not aware of the `text` property
> fix csg property extraction script

- CMakeModules/FindCLANG_FORMAT.cmake
updated so it finds clang-format-11 first and then tries for the general clang-format.
Also updated regex because ubuntu likes to put a "ubuntu" in front which breaks the regex otherwise.
> updated FindClang

- CHANGELOG.rst
- tools/src/libtools/histogram.cc
- tools/src/libtools/rangeparser.cc
Replaced the `std::bind2nd` with lambda expressions, since `bind2nd` is removed from C++17
> Fix deprecated bind2nd

- CHANGELOG.rst
- csg/src/libcsg/modules/io/lammpsdatareader.cc
In PR 703 of the CSG repo, a change was made where an error is thrown if you try to read a lammps file with bonds between molecules. (https://github.com/votca/csg/pull/703)
This change prevents us from loading a polymer in votca where the different monomers are labelled with a different molecule id. This is something we sometimes like to do in the XTP part. 
As a first suggestion I changed the `std::runtime_error` to a `std::cout`. In this way the user still gets notified of the bond between two different molecules, but the program won't terminate.
> Change error to warning

- CHANGELOG.rst
- xtp/src/libxtp/gwbse/gwbseengine.cc
- xtp/src/libxtp/jobcalculators/eqm.cc
- xtp/src/libxtp/jobcalculators/iqm.cc
The tasks_string parsing is done with the tokenizer now instead of string searches in the iqm calculator.
This should also be updated in eqm and the gwbseengine.
> properly parse tasks_string with tokenizer 

- CHANGELOG.rst
- xtp/src/libxtp/aobasis.cc
- xtp/src/tests/test_hdf5.cc
This fixes a bug in the basisset serialization that messed up the Vxc part of the GW calculation. 
@junghans this is a pretty serious bug and it would be great if we can get this change in before the new release
> Fix bug in basisset serialization

- CHANGELOG.rst
- tools/CMakeLists.txt
- tools/scripts/VOTCARC.bash.in
Originally added in votca/tools#340 for votca/xtp#673 (replaced #842 then #749)
Triggers a warning on python 3.10:
```
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
```
So if #749 ever gets close to being merged this needs to reverted (or added back to #749).
> cmake: remove PYTHON_INSTDIR

- .github/workflows/continuous-integration-workflow.yml
- CHANGELOG.rst
This reverts commit 70fd8f7ec4bcd7b302ab323aacd9183dc4011891 and
a60df23d6207351e7d3b47eb94c8a887ba921823 and hence parts of #940.
We can do this revert as #941 was fixed via https://github.com/votca/buildenv/pull/174.
> Revert "CI: ubuntu:latest is broken"

- CHANGELOG.rst
- tools/src/libtools/table.cc
Replacement for #955
Fix #955
Fix #954
> csg_resample will now generate an evenly spaced grid by scaling step [stable]

- CHANGELOG.rst
- csg/share/scripts/inverse/functions_common.sh
Fix #998 
Slightly better than #999 (I think)
> functions_common.sh: fix LC_ALL to C

- CHANGELOG.rst
- csg/share/scripts/inverse/inverse.sh
- csg/share/xml/csg_defaults.xml.in
This is needed for some future csg-tutorials where the pre folder is only used to obtain the initial guess. In that case it should only run step_000, independent of what `--do-iterations` (used by CI) says.
> changes to how csg_inverse checks how many steps to run

- CHANGELOG.rst
- xtp/src/pyxtp/pyxtp/options.py
- xtp/src/pyxtp/pyxtp/xml_editor.py
This small PR fixes the log issue raised in #1072 
The xml tree representing the option is now first copied internally instead of modified inplace before being written to file. This reduces the log file in case two calculations are performed once after the other using the same calculator instance (e.g. for a force calculation).
> Reduce warnings XML options not set in pyxtp 

- CHANGELOG.rst
- xtp-tutorials/CMakeLists.txt
> cmake: fix doc generation without pyxtp

- CHANGELOG.rst
- tools/CMakeLists.txt
Calling find_package(MKL) twice leads to MKL_FOUND being set to true even if it wasn't found.
> cmake: fix MKL detection

- .github/workflows/continuous-integration-workflow.yml
- CHANGELOG.rst
The intel package cannot be installed on Fedora 39+ anymore, and F38 will end of life in June, so let's try to switch to Ubuntu for the Intel builds.
> CI: run Intel build on Ubuntu

- .github/actions/setup/setup.sh
- CHANGELOG.rst
```
2024-03-29T05:20:36.1465244Z In file included from /__w/votca/votca/xtp/src/libxtp/aomatrices/aoecp.cc:27:
2024-03-29T05:20:36.1468514Z /usr/include/libint2/solidharmonics.h:218:45: error: 'iterator<std::input_iterator_tag, libint2::solidharmonics::SolidHarmonicsCoefficients<double>>' is deprecated [-Werror,-Wdeprecated-declarations]
2024-03-29T05:20:36.1471909Z   218 |         struct CtorHelperIter : public std::iterator<std::input_iterator_tag, SolidHarmonicsCoefficients> {
2024-03-29T05:20:36.1473369Z       |       
```
> CI: fix rawhide and opensuse warnings

- CHANGELOG.rst
- csg/src/libcsg/modules/io/pdbreader.cc
- xtp/src/libxtp/calculators/kmcmultiple.cc
Build was failing with Boost 1.85.0:
```
/tmp/votca-20240425-65266-25g6le/csg/src/libcsg/modules/io/pdbreader.cc:25:10: fatal error: 'boost/filesystem/convenience.hpp' file not found
#include <boost/filesystem/convenience.hpp>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
/tmp/votca-20240425-70011-caqdam/xtp/src/libxtp/calculators/kmcmultiple.cc:211:28: error: no template named 'numeric_cast' in namespace 'boost'; did you mean 'Eigen::internal::numeric_list'?
unsigned long maxsteps = boost::numeric_cast<unsigned long>(runtime_);
^~~~~~~~~~~~~~~~~~~
Eigen::internal::numeric_list
```
First error is due to `convenience.hpp` removal - https://www.boost.org/doc/libs/1_85_0/libs/filesystem/doc/deprecated.html. I didn't see any usage of `boost::filesystem` that would require this so just removed …
> Fix build with Boost 1.85.0

- CHANGELOG.rst
- xtp/CMakeLists.txt
If hdf5 is build with cmake, v1.12 doesn't satisfy the version requirement of v1.8 anymore as it counts it as incompatible, we let's drop version requirement in our cmake.
Related to #1124
> cmake: clean up hdf5 detection

- CHANGELOG.rst
- CONTRIBUTING.md
For the moment, could you add contributing guidelines to your project, and link to them in the README? They appear missing (examples here: https://contributing.md/example/).
_Originally posted by @Kevin-Mattheus-Moerman in https://github.com/openjournals/joss-reviews/issues/6795#issuecomment-2135125938_
> add CONTRIBUTING.md

- CHANGELOG.rst
- csg/share/scripts/inverse/csg_table
Having that additional space causes problems in `functions_common.sh` on some architectures.
> removing additonal space in csg_table
