.travis.yml
CMakeLists.txt
docker/Dockerfile

Enable code coverage

---

.travis.yml

travis: enable clang build

---

.travis.yml

Add Werror build

---

.travis.yml
share/doc/Doxyfile.in

Deploy manual and doxygen from superbuild

---

.travis.yml
docker/Dockerfile

Adding travis files to be used with other VOTCA modules.

---

.travis.yml

added gmx5.1 and master build

---

.travis.yml

Add ubuntu build 

---

CMakeLists.txt
CMakeModules/FindMKL.cmake

Fix #31
@JensWehner: please test.

Detect mkl and add incl. path

---

DEVELOPERS_GUIDE.md

Open to suggestions for this one.

Extra developer guide lines

---

docker/Dockerfile

Dockerfile: check that nothing was installed outside of prefix

---

.travis.yml

.travis.yml: added next branch feature

---

share/doc/DEVELOPERS_GUIDE.md

I have started this but I need some help. With merging across multiple repos simultaneously. @junghans I think you have tried to explain this to me before but I did not comprehend all the steps.

Made small changes to developers guide

---

.gitlab-ci.yml

add Gitlab artifacts

---

share/doc/DEVELOPERS_GUIDE.md

Describes how to use mock and qemu to run pcc64le.

Docs how to use mock2

---

share/doc/DEVELOPERS_GUIDE.md

Should be merged after: https://github.com/votca/votca/pull/121

Docs merging with stable

---

share/format/CMakeLists.txt

Test for https://github.com/votca/xtp/pull/238

cmake: re-enable format for xtp

---

.codecov.yml
.travis.yml
docker/Dockerfile
docker/set_env.sh

Improve codecov coverage

---

CMakeModules/FindCLANG_FORMAT.cmake
docker/Dockerfile
docker/set_env.sh
share/format/CMakeLists.txt

cmake: check for clang-format-7.0.1

---

share/doc/DEVELOPERS_GUIDE.md

Added documentation on gitlab-runner server.

Add infor on gitlab-runner server setup

---

docker/set_env.sh

Needed for https://github.com/votca/tools/pull/127

set_env.sh: exclude memory test on travis

---

.gitlab-ci.yml
docker/set_env.sh

Related to https://github.com/votca/csg/issues/387

gitlab-ci: disable gmx9999 build

---

docker/set_env.sh

More merges from development

---

share/doc/INSTALL.md

Remove some packages which are not needed anymore in the new rc

Updating dependencies

---

share/doc/INSTALL.md

To add to the random install error category

GCC and MKL linking errors

---

docker/set_env.sh

`-fix` doesn't work in all cases.

travis: disable tidy again

---

CMakeLists.txt

Replacement for https://github.com/votca/tools/pull/205

cmake: inject --no-as-needed for mkl + gcc

---

CMakeLists.txt
CMakeModules/BuildGromacs.cmake

For https://github.com/votca/csg/pull/511

fix build with gmx2021

---

.gitlab-ci.yml
.travis.yml
CMakeLists.txt
docker/set_env.sh
share/doc/CMakeLists.txt

Part of https://github.com/votca/xtp/pull/433

doc: inherit doc-xtp

---

CMakeLists.txt
README.md

Reported by user here:
https://groups.google.com/d/msg/votca/EeirrSPwcYM/Cccrh-CNAgAJ

cmake: warn user about missing submodules

---

share/doc/conf.py.in

Update master submodules

---

.github/workflows/make_release.sh
.github/workflows/release.yml

This will make the release workflow more automatic, I still need to test this more, but for that we have to merge it first.

Add release workflow

---

.github/workflows/make_release.sh
.github/workflows/release.yml

Same as #392 , but we need it on stable as well to trigger it there.

GHA: add release workflow to stable

---

.gitattributes
CMakeLists.txt

cmake: switch to new version scheme

---

share/doc/DEVELOPERS_GUIDE.rst
share/doc/VOTCA_LANGUAGE_GUIDE.rst

@junghans  please review if all is true
@baumeier  is it understandable?

moved some documentation and wrote basic paragraph about the CI

---

.github/workflows/make_release.sh
share/doc/INSTALL.rst

people do not seem to read it all 
Deleted legacy install instructions

Restructured install instructions, because

---

CMakeLists.txt
share/doc/extract_xml_metadata.py

https://github.com/votca/xtp/pull/603#issuecomment-736903874

doc: move extract_metadata.py from xtp

---

share/doc/index.rst

doc: add link to old page

---

share/doc/INSTALL.rst

For the 2021 release on that should happen automatically.

doc: update latest version in INSTALL.rst

---

share/doc/DEVELOPERS_GUIDE.rst
share/doc/INSTALL.rst
share/doc/VOTCA_LANGUAGE_GUIDE.rst

From https://github.com/votca/votca.github.io/pull/4 and https://github.com/votca/votca.github.io/pull/3

Josh's doc updates

---

.github/workflows/make_release.sh
.github/workflows/release.yml

This will create workflow new section in all CHANGELOG.rst automatically.

GHA: add next CHANGELOG secion in make_release.sh

---

.github/workflows/continuous-integration-workflow.yml
.github/workflows/stable_cron.yml

Workaround for  https://bugzilla.redhat.com/show_bug.cgi?id=1900021

GHA: try to fix rawhide build

---

.github/workflows/auto-cancel.yml
.github/workflows/stable_cron.yml

This might help with PRs to update the submodules.

GHA: add auto-cancel action

---

share/doc/extract_xml_metadata.py

fix [csg#618](https://github.com/votca/csg/issues/618) by swapping the *default values* with *description* in the documentation.

swap description and default value in the documentation

---

.github/workflows/continuous-integration-workflow.yml
.github/workflows/docker-build.yml
share/doc/_static/css/theme.css
share/doc/conf.py.in
share/doc/index.rst
share/doc/websiteAndDocumentation.rst

I have made it possible to change the theme of read the docs from within the votca repo and added a page on how to edit the website and documentation. 
I didn't try really hard to make the text nice or anything, so feel free to change things or update them.
Also if you don't like the theme change (I changed the width of the content field to 1200px, to make the table fit better and use a larger part of the screen) let me know.

Update of website

---

share/doc/DEVELOPERS_GUIDE.rst
share/doc/INSTALL.rst
share/doc/VOTCA_LANGUAGE_GUIDE.rst
share/doc/index.rst

I used https://www.w3.org/2002/01/spellchecker to find those

Fix some small typos in votca/votca

---

CMakeLists.txt

Testing https://github.com/votca/tools/pull/371

cmake: move all MKL stuff to tools

---

share/doc/DEVELOPERS_GUIDE.rst
share/doc/index.rst
share/doc/websiteAndDocumentation.rst

and some rst cleanup.
Fix #677

Website rework landingpage

---

share/doc/extract_xml_metadata.py

https://github.com/votca/xtp/pull/704 + https://github.com/votca/tools/pull/375 + https://github.com/votca/xtp-tutorials/pull/79

updated xtp and tools

---

tools/src/tests/CMakeLists.txt

valgrind finds errors with intel compiler

disabled broken random test

---

CHANGELOG.rst
tools/src/libtools/cubicspline.cc

fix warning: isnan is always false on intel

---

CHANGELOG.rst
CMakeLists.txt
csg-tutorials/CMakeLists.txt
csg/CMakeLists.txt
tools/CMakeLists.txt
xtp-tutorials/CMakeLists.txt
xtp/CMakeLists.txt

Bump required CMake version to 3.13

---

CHANGELOG.rst
xtp/src/libxtp/gwbse/gwbse.cc

Fixed incorrect passing of option to plot the energy dependence of the self-energy to the GW class.

sigma plot options are now properly passed through

---

CHANGELOG.rst
tools/src/tests/test_filesystem.cc

FreeBSD fixes

---

CHANGELOG.rst
xtp/src/libxtp/gwbse/gwbse.cc

fix for .quadrature_scheme

---

CHANGELOG.rst
xtp/include/votca/xtp/qmregion.h
xtp/share/xtp/xml/qmmm.xml
xtp/share/xtp/xml/subpackages/region.xml
xtp/src/libxtp/qmregion.cc

Seperating max density tolerance convergence from RMS density option

---

.github/actions/setup/setup.sh
CHANGELOG.rst

icpx dropped -no-debug-disables-optimization flag

CI: fix build with icpx

---

CHANGELOG.rst
xtp/scripts/xtp_autogen_mapping.in

`xtp_autogen_mapping` did not use the updated option handling properly.

fixed autogen_mapping options handling

---

.github/workflows/changelog-check.yml
CHANGELOG.rst

Our current changelog checker is broken, so let's implement your own.

CI: add changelog check

---

CHANGELOG.rst
xtp/src/tests/test_diabatization.cc

increase tolerance for diabatization test

---

CHANGELOG.rst
xtp/src/libxtp/progressobserver.cc
xtp/src/libxtp/statesaver.cc

swapped lock with sharable lock

---

CHANGELOG.rst
csg/include/votca/csg/interaction.h
csg/src/libcsg/modules/io/gmxtrajectoryreader.cc
csg/src/libcsg/trajectorywriter.cc
csg/src/tests/test_beadmotif_algorithms.cc
csg/src/tools/csg_fmatch.cc
csg/src/tools/csg_reupdate.cc
xtp/include/votca/xtp/energy_terms.h
xtp/src/libxtp/aomatrices/aoplanewave.cc
xtp/src/libxtp/aomatrices/aotransform.cc
xtp/src/libxtp/eeinteractor.cc
xtp/src/libxtp/grids/radial_euler_maclaurin_rule.cc
xtp/src/libxtp/gwbse/gwbse.cc
xtp/src/libxtp/jobcalculators/qmmm.cc
xtp/src/libxtp/libint2_calls.cc
xtp/src/libxtp/numerical_integration/density_integration.cc
xtp/src/libxtp/polarregion.cc
xtp/src/libxtp/qmpackages/orca.cc
xtp/src/libxtp/self_energy_evaluators/sigma_exact.cc

For https://github.com/Homebrew/homebrew-core/pull/129512

gmxtrajectoryreader: fix linking issue on OSX

---

.github/actions/changelog/changelog.sh
.github/workflows/changelog-check.yml
CHANGELOG.rst

Update changelog workflows

---

.github/workflows/make_release.sh
CHANGELOG.rst
CMakeLists.txt
xtp/include/votca/xtp/md2qmengine.h
xtp/src/libxtp/jobcalculators/eqm.cc
xtp/src/libxtp/jobcalculators/iqm.cc
xtp/src/libxtp/md2qmengine.cc
xtp/src/libxtp/qmregion.cc
xtp/src/libxtp/tools/molpol.cc
xtp/src/tests/test_orca.cc
xtp/src/tests/test_parallelism.cc

The pointer construct used in parsing the mapping information was unstable. Replaced it with a somewhat less efficient, but reliable approach.

Mapping without pointers

---

CHANGELOG.rst
xtp/src/libxtp/calculators/kmclifetime.cc
xtp/src/libxtp/calculators/neighborlist.cc

replaced deprecated boost::progress headers

---

.github/workflows/continuous-integration-workflow.yml
CHANGELOG.rst

CI: drop intel classic from CI

---

CHANGELOG.rst
tools/scripts/extract_xml_metadata.py
xtp-tutorials/pyxtp/scripts/run_energy.py
xtp-tutorials/pyxtp/scripts/run_gradient.py
xtp-tutorials/pyxtp/scripts/run_mapchecker.py
xtp-tutorials/pyxtp/scripts/run_optimization.py
xtp/src/pyxtp/pyxtp/capture_standard_output.py

Fedora complained about that and py2 is dead anyhow!

py: fix all shebangs

---

CHANGELOG.rst
xtp/include/votca/xtp/kmccalculator.h
xtp/share/xtp/xml/kmclifetime.xml
xtp/share/xtp/xml/kmcmultiple.xml
xtp/src/libxtp/kmccalculator.cc

new option to ignore segments of certain types in graph

---

papers/v2024/paper.bib
papers/v2024/paper.md

I've added a few sentences regarding pyxtp and a code snippet. I don't think we should extend that part too much as it is a relatively small component of VOTCA.  I don't have direct access to the repo hence the PR from my fork.

PyXTP [short] description and snippet 

---

CHANGELOG.rst
csg/scripts/CMakeLists.txt
csg/scripts/csg_call
csg/scripts/csg_inverse
csg/share/scripts/inverse/inverse.sh
csg/src/csg_boltzmann/CMakeLists.txt
csg/src/csgapps/CMakeLists.txt
csg/src/tools/CMakeLists.txt
tools/src/tools/CMakeLists.txt
xtp/scripts/CMakeLists.txt
xtp/src/tools/CMakeLists.txt

Related to #1124 to help to build on FreeBSD, but these change won't hurt on Linux either.

cmake: interpreter improvements

---

CHANGELOG.rst
csg/share/scripts/inverse/calc_density_generic.sh
csg/share/scripts/inverse/optimizer_state_to_mapping.sh
csg/share/scripts/inverse/prepare_optimizer_single.sh
csg/share/scripts/inverse/run_genericsim.sh

sh: use sed in posix way

---

.github/workflows/freebsd.yml
CHANGELOG.rst

CI: add build on FreeBSD

---

CHANGELOG.rst
CMakeLists.txt

This reverts commit 9de8e57f5f96c1f91f50ed455043cb59d12a5e13.

Revert "cmake: disable xtp-tutorials for now"

---

xtp-tutorials/pyxtp/geometry_optimization.ipynb

I'm trying to fix issue #1139 by removing the rattle function that may lead to unfavorable starting conformations for the optimization process and by limiting the number of steps.

fix geo opt tutorial

---

CHANGELOG.rst
csg-tutorials/hexane/atomistic/run.sh
csg-tutorials/hexane/hybrid_force_matching/run.sh
csg-tutorials/methanol-water/X_0.062/atomistic/run.sh
csg-tutorials/methanol-water/X_0.5/atomistic/run.sh
csg-tutorials/methanol-water/X_0.938/atomistic/run.sh
csg-tutorials/methanol/atomistic/run.sh
csg-tutorials/propane/atomistic/run.sh
csg-tutorials/propane/single_chain/run.sh
csg-tutorials/spce/atomistic/run.sh
csg-tutorials/spce/hncgn/settings.xml
csg-tutorials/urea-water/atomistic/run.sh

csg-tutorials: auto-detect gmx binary

---

CHANGELOG.rst
README.rst
share/sphinx/INSTALL.rst

For https://github.com/openjournals/joss-reviews/issues/6864#issuecomment-2219021275

ctest documentation

---

CHANGELOG.rst
csg-tutorials/methanol-water/X_0.062/re/run.sh
csg-tutorials/methanol-water/X_0.062/simplex/run.sh
csg-tutorials/methanol-water/X_0.5/re/run.sh
csg-tutorials/methanol-water/X_0.5/simplex/run.sh
csg-tutorials/methanol-water/X_0.938/re/run.sh
csg-tutorials/methanol-water/X_0.938/simplex/run.sh
csg-tutorials/propane/imc-ibiintra/pre/run.sh
csg-tutorials/propane/imc-ibiintra/run.sh
csg-tutorials/propane/imc/pre/run.sh
csg-tutorials/propane/imc/run.sh
csg-tutorials/propane/single_chain/run_fmatch.sh

scripts: fix exit code in tutorials

---

CHANGELOG.rst
papers/v2024.1/paper.md

This fixes some small formatting issues, mostly around references in the text.

Minor updates to JOSS paper

---

CHANGELOG.rst
xtp/src/libxtp/qmpackages/orca.cc

Newest ORCA release changed LOG file, adjusted the parser.

changed LOG reading for ORCA 6

---

.github/workflows/freebsd.yml
CHANGELOG.rst

CI: use vmactions/FreeBSD@v1

---

.github/workflows/docker-build.yml
CHANGELOG.rst
README.rst

CI: add arm64 docker build

---

CHANGELOG.rst
xtp/src/pyxtp/CMakeLists.txt

cmake: Fix python install

---

share/sphinx/xtp-tutorials/XTP-TUTORIAL.rst

Some tutorials were disabled. Re-enabling for #1176

Publishing tutorial
